#Create
price=899
rating=4.5
product_name="shirt"
avail=False
c=10+20j
#read
print(price)
print(rating)
print(product_name)
print(avail)
print(c)
#datatype
print(type(price))
print(type(rating))
print(type(product_name))
print(type(avail))
print(type(c)) 